name: Backup Repository

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2-6'

jobs:
  build:
    name: Run backup
    runs-on: ubuntu-latest
    environment: backup
    permissions:
      id-token: write
      contents: read
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Backup Shared Action
        uses: hrworks/hrworks-actions/.github/actions/aws-repo-backup-to-s3-bucket@main
        with:
          bundle-name: 'SmartFace'
          secret-gh-token: ${{ secrets.GITHUB_TOKEN }}
          aws-role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-bucket: ${{ vars.AWS_BUCKET }}
